cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views






urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  
    url('cart', include('cart.urls')),
    url('orders/', include('orders.urls')),
    url('', include('shop.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404 



app_name = 'shop'
handler404 = views.error_404

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/',views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^notfound/', views.notfound, name='notfound'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^edit/', views.edit, name='edit'),
    url(r'^newsletter/', views.newsletter, name='newsletter'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
  


        ] 




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

virtual/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from pyuploadcare.dj.models import ImageField
from django.db import models
from django.contrib.auth.models import User



# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True, manual_crop="4:4",)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class County(models.Model):
    name = models.CharField(max_length=60)
   

    def __str__(self):
        return self.name


class Profile(models.Model):
    profilePic = models.ImageField(upload_to='profile/',null=True,blank=True)
    bio = models.CharField(max_length=150,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True)
    
    
    def __str__(self):
        return self.bio

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def get_profile(cls):
        profile = Profile.objects.all()
        return profile

    @classmethod
    def find_profile(cls,search_term):
        profile = cls.objects.filter(user__username__icontains=search_term)
        return profile

    @classmethod
    def update_profile(cls,id,bio):
        updated = Image.objects.filter(id=id).update(bio = bio)
        return updated




class Image(models.Model):
    image = models.ImageField(upload_to='uploads/', blank=True, null=False)
    caption = models.CharField(max_length = 60)
    upload_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.caption
    class Meta:
        ordering = ['-upload_date']

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    @classmethod
    def update_caption(cls,id,caption):
        captioned = Image.objects.filter(id=id).update(caption = caption)
        return captioned

    @classmethod
    def get_images(cls):
        image = Image.objects.all()
        return image

    @classmethod
    def get_image_by_id(cls,id):
        image = Image.objects.filter(id=Image.id)
        return image

class Comment(models.Model):
    comments = models.CharField(max_length=60,blank=True,null=True)
    comment_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    def __str__(self):
        return self.comments

    class Meta:
        ordering = ['-comment_date']

    def save_comment(self):
        return self.save()

    def delete_comment(self):
        self.delete()

    @classmethod
    def get_comment(cls):
        comment = Comment.objects.all()
        return comment

shop/forms.py
from django import forms
from .models import Image,Profile,Comment,County

class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')





class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user',]

    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .forms import NewsLetterForm
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .email import send_welcome_email
from .models import Image,Profile,Comment,County
from .forms import EditProfileForm
from django.contrib.auth.models import User


@login_required(login_url='/accounts/login/')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)

@login_required(login_url='/accounts/login/')
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

@login_required(login_url='/accounts/login/')
def profile(request):
    title = 'Gumzo |profile'
    current_user = request.user
    profile = Profile.get_profile()
    image = Image.get_images()
    comments = Comment.get_comment()
    return render(request,'shop/profile/profile.html',{"title":title,
                                                  "comments":comments,
                                                  "image":image,
                                                  "user":current_user,
                                                  "profile":profile,})
@login_required(login_url='/accounts/login/')
def edit(request):
    title = 'Gumzo | edit profile'
    current_user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES)
        if form.is_valid():
            update = form.save(commit=False)
            update.user = current_user
            update.save()
            return redirect('/profile')
    else:
        form = EditProfileForm()
    return render(request,'shop/profile/edit.html',{"title":title,
                                                "form":form})


def error_404(request):
        data = {}
        return render(request,'shop/error_404.html', data)

                                               

def home(request):
  return render(request, 'shop/product/home.html')
  
def about(request):
  return render(request, 'shop/product/about.html')

def activity(request):
  return render(request, 'shop/product/activity.html')

def members(request):
  return render(request, 'shop/product/members.html')

def groups(request):
  return render(request, 'shop/product/groups.html')

def notfound(request):
  return render(request, 'shop/product/notfound.html')

def contact(request):
  return render(request, 'shop/product/contact.html')


def newsletter(request):
  
      if request.method == 'POST':
         form = NewsLetterForm(request.POST)
         if form.is_valid():
            email = form.cleaned_data['email']
            recipient = NewsLetterRecipients(email =email)
            recipient.save()
            HttpResponseRedirect('newsletter')
             
      else:
        form = NewsLetterForm()
      return render(request, 'shop/product/contact.html')


   

shop/templates/shop/profile/edit.html
{% extends 'shop/base.html' %}
{% load bootstrap4 %}
{% block content %}
{{block.super}}
<div class="container">
    <div class="row mt-5"></div>
    <div class="row mt-5"></div>
    <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
    <div class="card card-info mt-5">
        <div class="card-header">
            <h2>Edit Profile</h2>
        </div>
        <div class="card-body">
                <form action="{% url 'shop:edit' %}" id="EditProfileForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form-group">
                    <input type="submit" class="btn btn-info btn-sm" value="Post"  accept="image/*">
                </div>

                </form>
        </div>
    </div>
    </div>
    <div class="col-md-4"></div>
</div>
</div>

{% endblock %}

shop/templates/shop/profile/list_options.html
{% extends 'shop/base.html' %}
{% load bootstrap4 %}
{% block content %}
{{block.super}}}
<div class="container mt-5"></div>
<div class="container mt-5">
    <div class="row mt-1"></div>
    <div class="row mt-5">
    </div>
    <div class="row mt-5">
        {% for prof in profile %}
        {% if user.id == prof.user.id %}
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                {% if prof.profilePic %}
                    <img src="{{prof.profilePic.url}}" alt="" class="img-fluid" style="border-radius:50%">
                {% else %}
                    <img src="/static/img/avatar.png" alt="" class="img-fluid rounded-circle">
                {% endif %}
            </div>
            <div class="col-lg-1 col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
                {% if prof.bio %}
                    <h5>{{prof.user.username}}</h5>
                    <p>{{prof.bio}}</p>
                    <p>{{prof.county}}</p>
                {% else %}
                    <h5>{{prof.user.username}}</h5>
                {% endif %}
            </div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
        {% endif %}
        {% empty %}
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <img src="/static/img/avatar.png" alt="" class="img-fluid rounded-circle">
            </div>
            <div class="col-lg-1 col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
                <p>{{user.username}}</p>
            </div>
        </div>
        {% endfor %}
        <hr>
    </div>
    <hr>
    <div class="container">
        <div class="row">
                {% for img in image%}
            {% if img.user.id == user.id %}
            <div class="col-md-4 col-lg-4 col-sm-8 col-xs-8">
                    {% if img.image %}
                    <div class="card">
                        <div class="card-header">
                                <img src="{{img.profile.profilePic.url}}" class="img-fluid rounded-circle" style="width:8%;height:8%">
                                {% if user.id == img.user.id %}
                                <a href="{% url 'profile' %}">{{img.user.username}}</a>
                                {% else %}
                                <a href="#">{{img.user.username}}</a>
                                {% endif %}
                        </div>
                        <div class="card-body">
                            {% if img.image.url %}
                                <img src="{{img.image.url}}" alt="img-fluid" style="width:100%; height:100%">
                                <p>{{img.caption}}</p>
                                <p>{{img.upload_date | timesince}} ago</p>
                                {% if img.likes >= 1 %}
                                <p><i class="fa fa-heart fa-2x ml-4" style="color:red"></i><b>{{img.likes}} likes</b></p>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="card-footer">
                                {% for comment in comments %}
                                {% if img.id == comment.image.id %}
                                <p><b>{{comment.user}}</b>  {{comment.comments}}</p>
                                <h6  style="font-size:12px"><i>{{comment.comment_date | timesince}} ago</i></h6>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
            </div>
            {% endif %}
            {% endfor %}
       
            {% endblock %}

shop/templates/shop/profile/view.html
{% extends 'shop/base.html'%}
{% load bootstrap4 %}
{% load static %}
{% block content %}
{{block.super}}
<div class="container mt-5"></div>
<div class="container mt-5">
    <div class="container">
    <div class="row mt-5"></div>
    <div class="row mt-5"></div>
    <div class="row mt-5">

        {% for prof in profile %}
        {% if my_user.id == prof.user.id %}
        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            {% if prof.profilePic %}
                <img src="{{prof.profilePic.url}}" alt="" class="img-fluid" style="border-radius:50%">
            {% else %}
                <img src="/static/img/avatar.png" alt="" class="img-fluid rounded-circle">
            {% endif %}
        </div>
        <div class="col-lg-1 col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
            {% if prof.bio %}
                <h5>{{prof.user.username | title}}  <button class="btn btn-primary" href="#">Follow</button></h5>
                <p>{{prof.bio}}</p>
            {% else %}
                <h5>{{prof.user.username | title}}</h5>
            {% endif %}
        </div>
        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
        {% endif %}
        {% endfor %}
    </div>
</div>
</div>
<hr>
<div class="container">
    <div class="row">
        {% for img in images %}
        {% if my_user.id == img.user.id %}
            <div class="col-md-4 col-lg-4 col-sm-8 col-xs-8">
                {% if img.image %}
                <div class="card">
                        <div class="card-header">
                                <img src="{{img.profile.profilePic.url}}" class="img-fluid rounded-circle" style="width:8%;height:8%">
                                {% if user.id == img.user.id %}
                                <a href="{% url 'profile' %}">{{img.user.username}}</a>
                                {% else %}
                                <a href="#">{{img.user.username}}</a>
                                {% endif %}
                        </div>
                        <div class="card-body">
                            {% if img.image.url %}
                                <img src="{{img.image.url}}" alt="img-fluid" style="width:100%; height:100%">
                                <p>{{img.caption}}</p>
                                <p>{{img.upload_date | timesince}} ago</p>
                                {% if img.likes >= 1 %}
                                <p><i class="fa fa-heart fa-2x ml-4" style="color:red"></i><b>{{img.likes}} likes</b></p>
                                {% endif %}
                            {% endif %}
                            </div>
                        <div class="card-footer">
                                {% for comment in comments %}
                                {% if img.id == comment.image.id %}
                                <p><b>{{comment.user}}</b>  {{comment.comments}}</p>
                                <h6 style="font-size:12px"><i>{{comment.comment_date | timesince}} ago</i></h6>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                {% endif %}
            </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}