cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views






urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  
    url('cart', include('cart.urls')),
    url('orders/', include('orders.urls')),
    url('', include('shop.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404 



app_name = 'shop'
handler404 = views.error_404

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/',views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^notfound/', views.notfound, name='notfound'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^edit/', views.edit, name='edit'),
    url(r'^newsletter/', views.newsletter, name='newsletter'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
  


        ] 




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

virtual/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from pyuploadcare.dj.models import ImageField
from django.db import models
from django.contrib.auth.models import User



# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True, manual_crop="4:4",)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class County(models.Model):
    name = models.CharField(max_length=60)
   

    def __str__(self):
        return self.name


class Profile(models.Model):
    profilePic = models.ImageField(upload_to='profile/',null=True,blank=True)
    bio = models.CharField(max_length=150,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True)
    
    
    def __str__(self):
        return self.bio

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def get_profile(cls):
        profile = Profile.objects.all()
        return profile

    @classmethod
    def find_profile(cls,search_term):
        profile = cls.objects.filter(user__username__icontains=search_term)
        return profile

    @classmethod
    def update_profile(cls,id,bio):
        updated = Image.objects.filter(id=id).update(bio = bio)
        return updated




class Image(models.Model):
    image = models.ImageField(upload_to='uploads/', blank=True, null=False)
    caption = models.CharField(max_length = 60)
    upload_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.caption
    class Meta:
        ordering = ['-upload_date']

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    @classmethod
    def update_caption(cls,id,caption):
        captioned = Image.objects.filter(id=id).update(caption = caption)
        return captioned

    @classmethod
    def get_images(cls):
        image = Image.objects.all()
        return image

    @classmethod
    def get_image_by_id(cls,id):
        image = Image.objects.filter(id=Image.id)
        return image

class Comment(models.Model):
    comments = models.CharField(max_length=60,blank=True,null=True)
    comment_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    def __str__(self):
        return self.comments

    class Meta:
        ordering = ['-comment_date']

    def save_comment(self):
        return self.save()

    def delete_comment(self):
        self.delete()

    @classmethod
    def get_comment(cls):
        comment = Comment.objects.all()
        return comment

shop/forms.py
from django import forms
from .models import Image,Profile,Comment,County

class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')





class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user',]

    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .forms import NewsLetterForm
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .email import send_welcome_email
from .models import Image,Profile,Comment,County
from .forms import EditProfileForm
from django.contrib.auth.models import User


@login_required(login_url='/accounts/login/')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)

@login_required(login_url='/accounts/login/')
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

@login_required(login_url='/accounts/login/')
def profile(request):
    title = 'Gumzo |profile'
    current_user = request.user
    profile = Profile.get_profile()
    image = Image.get_images()
    comments = Comment.get_comment()
    return render(request,'shop/profile/profile.html',{"title":title,
                                                  "comments":comments,
                                                  "image":image,
                                                  "user":current_user,
                                                  "profile":profile,})
@login_required(login_url='/accounts/login/')
def edit(request):
    title = 'Gumzo | edit profile'
    current_user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES)
        if form.is_valid():
            update = form.save(commit=False)
            update.user = current_user
            update.save()
            return redirect('/profile')
    else:
        form = EditProfileForm()
    return render(request,'shop/profile/edit.html',{"title":title,
                                                "form":form})


def error_404(request):
        data = {}
        return render(request,'shop/error_404.html', data)

                                               

def home(request):
  return render(request, 'shop/product/home.html')
  
def about(request):
  return render(request, 'shop/product/about.html')

def activity(request):
  return render(request, 'shop/product/activity.html')

def members(request):
  return render(request, 'shop/product/members.html')

def groups(request):
  return render(request, 'shop/product/groups.html')

def notfound(request):
  return render(request, 'shop/product/notfound.html')

def contact(request):
  return render(request, 'shop/product/contact.html')


def newsletter(request):
  
      if request.method == 'POST':
         form = NewsLetterForm(request.POST)
         if form.is_valid():
            email = form.cleaned_data['email']
            recipient = NewsLetterRecipients(email =email)
            recipient.save()
            HttpResponseRedirect('newsletter')
             
      else:
        form = NewsLetterForm()
      return render(request, 'shop/product/contact.html')


   

shop/templates/shop/product/contact.html
{% extends 'shop/base.html' %}
{% load static %}



{% block content %}



<!-- //Modal2 -->
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
		<div class="container">
			<h3>C<span>ontact Us </span></h3>
			<!--/w3_short-->
				 <div class="services-breadcrumb">
						<div class="agile_inner_breadcrumb">

						   <ul class="w3_short">
								<li><a href="{% url 'shop:home' %}">Home</a><i>|</i></li>
								<li>Contact</li>
							</ul>
						 </div>
				</div>
	   <!--//w3_short-->
	</div>
</div>
   <!--/contact-->
    <div class="banner_bottom_agile_info">
	    <div class="container">
		  <div class="contact-grid-agile-w3s">
				<div class="col-md-4 contact-grid-agile-w3">
						<div class="contact-grid-agile-w31">
							<i class="fa fa-map-marker" aria-hidden="true"></i>
							<h4>Address</h4>
							<p>Greenfields <span>Nairobi , Kenya</span></p>
						</div>
					</div>
					<div class="col-md-4 contact-grid-agile-w3">
						<div class="contact-grid-agile-w32">
							<i class="fa fa-phone" aria-hidden="true"></i>
							<h4>Call Us</h4>
							<p>+254 723615755<span>+254 726830125</span></p>
						</div>
					</div>
					<div class="col-md-4 contact-grid-agile-w3">
						<div class="contact-grid-agile-w33">
							<i class="fa fa-envelope-o" aria-hidden="true"></i>
							<h4>Email</h4>
							<p><a href="mailto:info@example.com">info@Gumzoclub.com</a><span><a href="mailto:info@example.com">beryl@Gumzoclub.com</a></span></p>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
	   </div>
	 </div>

  
				<div class="clearfix"> </div>
			</div>
       </div>
	</div>
 <!--//contact-->
<!--/grids-->

<!--grids-->
<!-- footer -->

	<!-- Footer Section Start -->
	<footer class="footer--section">
			<!-- Footer Widgets Start -->
			<div class="footer--widgets pt--70 pb--20 bg-lightdark" data-bg-img="img/footer-img/footer-widgets-bg.png">
				<div class="container">
					<div class="row AdjustRow">
						<div class="col-md-3 col-xs-6 col-xxs-12 pb--60">
							<!-- Widget Start -->
							<div class="widget">
								<h2 class="h4 fw--700 widget--title">About Us</h2>
	
								<!-- Text Widget Start -->
								<div class="text--widget">
									<p>Ipsum is simply dummy text of the printing indusLorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
	
									<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
								</div>
								<!-- Text Widget End -->
							</div>
							<!-- Widget End -->
	
										 <!-- Widget Start -->
										 <div class="widget">
												<h2 class="h4 fw--700 widget--title">Subscribe To Our Newsletter</h2>
				
												<!-- Newsletter Widget Start -->
												<div class="newsletter--widget style--1" data-form="validate">
													<!-- <form action="https://themelooks.us13.list-manage.com/subscribe/post?u=79f0b132ec25ee223bb41835f&amp;id=f4e0e93d1d" method="post" name="mc-embedded-subscribe-form" target="_blank"> -->
														<form  action="{%url 'shop:newsletter'%}" method="post"></form>
														{%csrf_token%}
														<div class="input-group">
															<input type="email" name="EMAIL" placeholder="Enter your emil address" class="form-control" autocomplete="off" required>
				
															<div class="input-group-btn">
																	<button type="submit" class="btn-link"><i class="fa fa-send-o"></i></button>
															</div>
														</div>
													</form>
												</div>
												<!-- Newsletter Widget End -->
											</div>
											<!-- Widget End -->
										</div>
				
										<div class="col-md-3 col-xs-6 col-xxs-12 pb--60">
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">Recent Post</h2>
				
												<!-- Recent Posts Widget Start -->
												<div class="recent-posts--widget">
													<ul class="nav">
														<li>
															<p class="date fw--300">
																<a href="#"><i class="fa mr--8 fa-file-text-o"></i>19 Jan 2019</a>
															</p>
															<p class="title fw--700">
																<a href="blog-details.html">looking for  poultry frmers group to join</a>
															</p>
														</li>
														<li>
															<p class="date fw--300">
																<a href="#"><i class="fa mr--8 fa-file-text-o"></i>19 Jan 2019</a>
															</p>
															<p class="title fw--700">
																<a href="blog-details.html">what are the most effective marketing ideas</a>
															</p>
														</li>
														<li>
															<p class="date fw--300">
																<a href="#"><i class="fa mr--8 fa-file-text-o"></i>19 Jan 2017</a>
															</p>
															<p class="title fw--700">
																<a href="blog-details.html">2019 waiting for the goverments budget</a>
															</p>
														</li>
													</ul>
												</div>
												<!-- Recent Posts Widget End -->
											</div>
											<!-- Widget End -->
				
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">Tags</h2>
				
												<!-- Tags Widget Start -->
												<div class="tags--widget">
													<ul class="nav">
														<li><a href="#">Farming</a></li>
														<li><a href="#">Politics</a></li>
														<li><a href="#">Music</a></li>
														<li><a href="#">Technology</a></li>
														<li><a href="#">kenya</a></li>
														<li><a href="#">Photography</a></li>
														<li><a href="#">Gumzoclub</a></li>
													</ul>
												</div>
												<!-- Tags Widget End -->
											</div>
											<!-- Widget End -->
										</div>
				
										<div class="col-md-3 col-xs-6 col-xxs-12 pb--60">
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">Some of Catagories</h2>
				
												<!-- Nav Widget Start -->
												<div class="nav--widget">
													<ul class="nav">
														<li>
															<a href="#">
																<i class="fa fa-folder-o"></i>
																<span class="text">Farming</span>
																<span class="count">(26)</span>
															</a>
														</li>
														<li>
															<a href="#">
																<i class="fa fa-folder-o"></i>
																<span class="text">volunteer work</span>
																<span class="count">(06)</span>
															</a>
														</li>
														<li>
															<a href="#">
																<i class="fa fa-folder-o"></i>
																<span class="text">Services</span>
																<span class="count">(34)</span>
															</a>
														</li>
													</ul>
												</div>
												<!-- Nav Widget End -->
											</div>
											<!-- Widget End -->
				
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">From Archives</h2>
				
												<!-- Nav Widget Start -->
												<div class="nav--widget">
													<ul class="nav">
														<li>
															<a href="#">
																<i class="fa fa-calendar-o"></i>
																<span class="text">Jan - July 2017</span>
																<span class="count">(86)</span>
															</a>
														</li>
														<li>
															<a href="#">
																<i class="fa fa-calendar-o"></i>
																<span class="text">Jan - Dce 2016</span>
																<span class="count">(328)</span>
															</a>
														</li>
														<li>
															<a href="#">
																<i class="fa fa-calendar-o"></i>
																<span class="text">Jan - Dec 2015</span>
																<span class="count">(427)</span>
															</a>
														</li>
													</ul>
												</div>
												<!-- Nav Widget End -->
											</div>
											<!-- Widget End -->
										</div>
				
										<div class="col-md-3 col-xs-6 col-xxs-12 pb--60">
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">Forums</h2>
				
												<!-- Links Widget Start -->
												<div class="links--widget">
													<ul class="nav">
														<li><a href="sub-forums.html">Best farming practices in Nairobi</a></li>
														<li><a href="sub-forums.html">Poultry farmers</a></li>
														<li><a href="sub-forums.html">Communities to join</a></li>
														<li><a href="sub-forums.html">Social Media Marketing</a></li>
														<li><a href="sub-forums.html">Product Marketing</a></li>
													</ul>
												</div>
												<!-- Links Widget End -->
											</div>
											<!-- Widget End -->
				
											<!-- Widget Start -->
											<div class="widget">
												<h2 class="h4 fw--700 widget--title">Useful Links</h2>
				
												<!-- Links Widget Start -->
												<div class="links--widget">
													<ul class="nav">
														<li><a href="#">Register</a></li>
														<li><a href="#">Gumzo club</a></li>
														<li><a href="#">Membership </a></li>
														<li><a href="#">Shop</a></li>
														<li><a href="#">Contact members</a></li>
													</ul>
												</div>
												<!-- Links Widget End -->
											</div>
											<!-- Widget End -->
										</div>
									</div>
								</div>
							</div>
							<!-- Footer Widgets End -->


  {% endblock %}

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main" >

          <div class="blog-post" >
              <div class="row">
                <div class="card" >
                    <div class="card-body" >
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %} {{ product.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt="..." style="height: 220px; width: auto; box-shadow: 0px 5px 4px rgba(0, 0, 0, 0.3);">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px ">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">Kshs. {{ product.price }}</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-warning">
                            </form>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

shop/templates/shop/product/homeaccesories.html
{% extends 'shop/base.html' %}
{% load static %}



{% block content %}
<div class="col-md-4 modal_body_right modal_body_right1">

					</div>
				</div>
			</div>
			<!-- //Modal content-->
		</div>
	</div>
<!-- //Modal2 -->
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
	<div class="container">
		<h3>Home<span> ACCESORIES </span></h3>
		<h3><span>COMING</span>SOON</h3>
		<!--/w3_short-->
			 <div class="services-breadcrumb">
					<div class="agile_inner_breadcrumb">

						 <ul class="w3_short">
							<li><a href="{% url 'shop:home' %}">Home</a><i>|</i></li>
							<li>HOME Accesories</li>
						</ul>
					 </div>
			</div>
	 <!--//w3_short-->
</div>
</div>
  {% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
    {% if category %}{{ category.name }} {% else %} GUMZO | SOKO {% endif %}
{% endblock %}

{% block content %}

<div class="top_nav_right">
  <div class="box_1">

    {% with totail_items=cart|length %}
      {% if cart|length > 0 %}
        My Shopping Order:
        <a href="{% url 'cart:cart_detail' %}" >
          {{ totail_items }} <button type="button" class="btn btn-primary btn-lg">item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}</button>
        </a>
        {% else %}
        Your cart is empty.  {{ totail_items }}  {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
      {% endif %}
    {% endwith %}

      </div>
  </div>
   <div class="container-fluid">
      <div class="row" style="margin-top: 0%">
        <div class="col-sm-3 " >
          <br>
          <div class="css-treeview" style=" box-shadow: 1px 5px 4px rgba(0, 0, 0, 0.3);">
    				<h4>Categories</h4>
            	<ul class="tree-list-pad">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
          </ul>
          </div>
        </div><!-- /.blog-sidebar -->
        <div class="tab2">
          {% for product in products %}
           <div class="col-md-3 product-men">
            <div class="men-pro-item simpleCart_shelfItem">
              <div class="men-thumb-item">
                <img src="{% if product.image %} {{ product.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}"  alt="" class="pro-image-front">
                <img src="{% if product.image %} {{ product.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}"  alt="" class="pro-image-back">
                  <div class="men-cart-pro">
                    <div class="inner-men-cart-pro">
                      <a href="{{ product.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
                    </div>
                  </div>
                  
              </div>
              <div class="item-info-product ">
                <h4><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                <div class="info-product-price">
                  <span class="item_price">Kshs. {{ product.price }}</span>

                </div>
                <!--  -->
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">

                                <a href="{{ product.get_absolute_url }}"><input type="submit" name="submit" value="Add to cart" class="button" />
                                </a>
                          </div>
              </div>
            </div>
          </div>
  {% endfor %}
  <br>
  <br>
  <br>
  <br>
  <div class="row">
      {% if products%}
      {% else %}
        <h1><strong>sorry </strong>nothing found in selected category .</h1>
        <h3> <a href="{% url 'shop:contact' %}">contact</a> us if you wish to sell products on gumzo soko</h3>
        <h4>or kindly visit this page soon to find items</h4>
        <h6><a href="{% url 'shop:product_list' %}">continue shopping</a></h6>
        <br>
        
      {% endif %}
  
    </div>
  <a href="{% url 'shop:product_list' %}" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


    </div>
  </div>
</div>
{% endblock %}

shop/templates/shop/product/notfound.html
{% extends 'shop/base.html' %}

{% load static %}


{% block content %} 
 
 
 <!-- Wrapper Start -->

 <div class="wrapper">
        <!-- 404 Section Start -->
        <div class="f0f--section">
            <div class="f0f--bg hidden-xs">
                <div class="f0f--bg-inner" data-bg-img="img/light-bg.png"></div>
            </div>

            <div class="vc--parent">
                <div class="vc--child">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <!-- 404 Content Start -->
                                <div class="f0f--content text-white text-center pt--80 pb--80">
                                    <div class="caption fs--18 fw--700 text-uppercase">
                                        <p>this page will be up soon</p>
                                    </div>

                                    <div class="title fw--700">
                                        <p>404</p>
                                    </div>

                                    <div class="desc fs--18 fw--500">
                                        <p>The page you are looking for is temporary unavailable.Our team of engineers are working to resolve the issue, We will be back in a few</p>
      
                                    </div>

                                    <!-- Search Widget Start -->
                                    <div class="search--widget" data-form="validate">
                                        <form action="#">
                                            <input type="text" name="search" placeholder="Search" class="form-control" required>

                                            <button type="submit" class="btn-link"><i class="fa fa-search"></i></button>
                                        </form>
                                    </div>
                                    <!-- Search Widget End -->

                                    <div class="buttons">
                                        <a href="{% url 'shop:home' %}"class="btn btn-white">Go To Home<i class="fa fa-home"></i></a>

                                       
                                    </div>

                                    <div class="social pt--60">
                                        <ul class="nav">
                                            <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                            <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                            <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                            <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                            <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- 404 Content End -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 404 Section End -->
    </div>
    <!-- Wrapper End -->
    {% endblock %}