cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views






urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  
    url('cart', include('cart.urls')),
    url('orders/', include('orders.urls')),
    url('', include('shop.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404 



app_name = 'shop'
handler404 = views.error_404

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/',views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^notfound/', views.notfound, name='notfound'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^edit/', views.edit, name='edit'),
    url(r'^newsletter/', views.newsletter, name='newsletter'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
  


        ] 




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

virtual/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from pyuploadcare.dj.models import ImageField
from django.db import models
from django.contrib.auth.models import User



# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True, manual_crop="4:4",)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class County(models.Model):
    name = models.CharField(max_length=60)
   

    def __str__(self):
        return self.name


class Profile(models.Model):
    profilePic = models.ImageField(upload_to='profile/',null=True,blank=True)
    bio = models.CharField(max_length=150,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True)
    
    
    def __str__(self):
        return self.bio

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def get_profile(cls):
        profile = Profile.objects.all()
        return profile

    @classmethod
    def find_profile(cls,search_term):
        profile = cls.objects.filter(user__username__icontains=search_term)
        return profile

    @classmethod
    def update_profile(cls,id,bio):
        updated = Image.objects.filter(id=id).update(bio = bio)
        return updated




class Image(models.Model):
    image = models.ImageField(upload_to='uploads/', blank=True, null=False)
    caption = models.CharField(max_length = 60)
    upload_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.caption
    class Meta:
        ordering = ['-upload_date']

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    @classmethod
    def update_caption(cls,id,caption):
        captioned = Image.objects.filter(id=id).update(caption = caption)
        return captioned

    @classmethod
    def get_images(cls):
        image = Image.objects.all()
        return image

    @classmethod
    def get_image_by_id(cls,id):
        image = Image.objects.filter(id=Image.id)
        return image

class Comment(models.Model):
    comments = models.CharField(max_length=60,blank=True,null=True)
    comment_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    def __str__(self):
        return self.comments

    class Meta:
        ordering = ['-comment_date']

    def save_comment(self):
        return self.save()

    def delete_comment(self):
        self.delete()

    @classmethod
    def get_comment(cls):
        comment = Comment.objects.all()
        return comment

shop/forms.py
from django import forms
from .models import Image,Profile,Comment,County

class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')





class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user',]

    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .forms import NewsLetterForm
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .email import send_welcome_email
from .models import Image,Profile,Comment,County
from .forms import EditProfileForm
from django.contrib.auth.models import User


@login_required(login_url='/accounts/login/')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)

@login_required(login_url='/accounts/login/')
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

@login_required(login_url='/accounts/login/')
def profile(request):
    title = 'Gumzo |profile'
    current_user = request.user
    profile = Profile.get_profile()
    image = Image.get_images()
    comments = Comment.get_comment()
    return render(request,'shop/profile/profile.html',{"title":title,
                                                  "comments":comments,
                                                  "image":image,
                                                  "user":current_user,
                                                  "profile":profile,})
@login_required(login_url='/accounts/login/')
def edit(request):
    title = 'Gumzo | edit profile'
    current_user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES)
        if form.is_valid():
            update = form.save(commit=False)
            update.user = current_user
            update.save()
            return redirect('/profile')
    else:
        form = EditProfileForm()
    return render(request,'shop/profile/edit.html',{"title":title,
                                                "form":form})


def error_404(request):
        data = {}
        return render(request,'shop/error_404.html', data)

                                               

def home(request):
  return render(request, 'shop/product/home.html')
  
def about(request):
  return render(request, 'shop/product/about.html')

def activity(request):
  return render(request, 'shop/product/activity.html')

def members(request):
  return render(request, 'shop/product/members.html')

def groups(request):
  return render(request, 'shop/product/groups.html')

def notfound(request):
  return render(request, 'shop/product/notfound.html')

def contact(request):
  return render(request, 'shop/product/contact.html')


def newsletter(request):
  
      if request.method == 'POST':
         form = NewsLetterForm(request.POST)
         if form.is_valid():
            email = form.cleaned_data['email']
            recipient = NewsLetterRecipients(email =email)
            recipient.save()
            HttpResponseRedirect('newsletter')
             
      else:
        form = NewsLetterForm()
      return render(request, 'shop/product/contact.html')


   

shop/templates/shop/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GUMZO | WELCOME{% endblock %}</title>
   
   
   
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700%7CRoboto:300,400,400i,500,700">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">  
                                
    <!-- <link rel="shortcut icon" type="image/png" href="{% static 'images/topicon.png' %}"/> -->

     
   <link rel="stylesheet" href="{% static 'css/main.css' %}">
   <link rel="stylesheet" href="{% static 'css/registration.css' %}">
   <link rel="stylesheet" href=" {% static 'css/gumzostyle.css '% } "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/gumzoresponsive-style.css '%} "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/gumzocustom.css '%} "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/gumzoplugins.min.css '%} "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/gumzostyle.css' %} "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/styles.css' %} "type="text/css" media="all">
   <link rel="stylesheet" href=" {% static 'css/style.css' %} "type="text/css" media="all">
    
   <!-- //for bootstrap working -->
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700%7CRoboto:300,400,400i,500,700">
   <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
   <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <script>
        UPLOADCARE_PUBLIC_KEY = '1cbad0e210e9fd113e96';
        UPLOADCARE_TABS = 'file camera url facebook gdrive gphotos dropbox instagram evernote onedrive';
        UPLOADCARE_EFFECTS = 'crop,rotate,flip';
        UPLOADCARE_IMAGE_SHRINK = '1024x1024 60%';
        UPLOADCARE_IMAGES_ONLY = true;
        UPLOADCARE_PREVIEW_STEP = true;
        UPLOADCARE_CLEARABLE = true;
      </script>
      
      <script src="https://ucarecdn.com/libs/widget/3.x/uploadcare.full.min.js"></script><script src="https://ucarecdn.com/libs/widget-tab-effects/1.x/uploadcare.tab-effects.js"></script>
      <script>
        uploadcare.registerTab('preview', uploadcareTabEffects)
      </script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>
 
  <!-- ==== Plugins Bundle ==== -->
  <script src=" {% static 'js/modernizr-2.8.3.min.js' %}" type="text/javascript"></script>
  <script src=" {% static  'js/jquery-1.12.0.min.js'  %}" type="text/javascript"></script>
  <script src="{% static 'js/gumzoplugins.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/gumzomain.js' %}"></script> 
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/plugins/animate-headline.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

{% block content %}


{% endblock %}


</body>
</html>

shop/templates/shop/basehome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- First include jquery js -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=ABeeZee|Architects+Daughter|PT+Sans+Caption|Poppins|Sriracha|Varela" rel="stylesheet">
  <!-- Latest compiled and minified CSS -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="{% static 'css/homecss.css' %}">
</head>
<body>
 

{% block content %}


{% endblock %}


</body>
</html>

shop/templates/shop/navbar.html
{% load static %}



          

<!--  header Login signup nav  ------------>

<!--  //end of header Login signup nav  ----------------------------------------->




<!-- new nav --------------------------------------------------------------------->

<header>
		
		<!-- Header Navbar Start -->
		<div class="header--navbar navbar bg-black" data-trigger="sticky">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle style--1 collapsed" data-toggle="collapse" data-target="#headerNav">
						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<!-- Header Navbar Logo Start -->
					<div class="header--navbar-logo navbar-brand">
						<a href="{% url 'shop:home' %}">
							<img src="static/img/GUMZOLOGO.png" class="normal" alt="">
							<img src="static/img/GUMZOLOGO.png" class="sticky" alt="">
						</a>
					</div>
					<!-- Header Navbar Logo End -->
				</div>

				<div id="headerNav" class="navbar-collapse collapse float--right">
					<!-- Header Nav Links Start -->
					<ul class="header--nav-links style--1 nav ff--primary">
							<li class="dropdown active">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										<span>Home</span>
										<i class="fa fa-caret-down"></i>
									</a>
	
									<ul class="dropdown-menu">
										<li class="active"><a href="{% url 'shop:home' %}"><span>Welcome</span></a></li>
									  
									</ul>
								</li>
					
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span>Community</span>
								<i class="fa fa-caret-down"></i>
							</a>

							<ul class="dropdown-menu">
								<li><a href="{% url 'shop:notfound' %}"><span>Activity</span></a></li>
								<li><a href="{% url 'shop:notfound' %}"><span>Members</span></a></li>
								<li><a href="{% url 'shop:notfound' %}"><span>Groups</span></a></li>
							</ul>
						</li>
						
						<li class="dropdown megamenu">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span>Explore</span>
								<i class="fa fa-caret-down"></i>
							</a>

							<div class="dropdown-menu">
								<div class="row">
									<ul class="col-md-2">
										<li><a href="{% url 'shop:notfound' %}">Members</a></li>
										<li><a href="{% url 'shop:notfound' %}">Groups</a></li>
										<li><a href="{% url 'shop:notfound' %}">Site Wide Activity</a></li>
										
									</ul>

							   
									
									<ul class="col-md-2">
									   
										<li><a href="{% url 'shop:notfound' %}">Topics</a></li>
										
									</ul>
									
									<ul class="col-md-2">
										<li><a href="{% url 'shop:product_list' %}">Shop</a></li> <!-- Products.html-->
										<!-- <li><a href="product-details.html">Product Details</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="checkout.html">Checkout</a></li>
										<li><a href="#">Dummy</a></li> -->
									</ul>
									
									<ul class="col-md-2">
										<li><a href="{% url 'shop:notfound' %}">Blog</a></li >  <!--blog-sidebar-right.html-->
										<!-- <li><a href="blog-sidebar-left.html">Blog Sidebar Left</a></li>
										<li><a href="blog-details.html">Blog Details</a></li>
										<li><a href="#">Dummy</a></li>
										<li><a href="#">Dummy</a></li> -->
									</ul>
									
									<ul class="col-md-2">
										<li><a href="{% url 'shop:notfound' %}">About</a></li> <!--about.html-->
										<li><a href="{% url 'shop:notfound' %}">FAQ</a></li>     <!--faq.html-->
										<li><a href="{% url 'shop:contact' %}">Contact</a></li>  <!--contact.html-->
										<!-- <li><a href="coming-soon.html">Coming Soon</a></li>
										<li><a href="404.html">404</a></li> -->
									</ul>
								</div>
							</div>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span>Products</span>
								<i class="fa fa-caret-down"></i>
							</a>

							<ul class="dropdown-menu">
								<li><a href="{% url 'shop:product_list' %}">Shop</a></li> <!--products.htm-->
								<!-- <li><a href="product-details.html">Product Details</a></li> 
								<li><a href="cart.html">Cart</a></li> 
								<li><a href="checkout.html">Checkout</a></li>  -->
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span>Blog</span>
								<i class="fa fa-caret-down"></i>
							</a>

							<ul class="dropdown-menu">
								<li><a href="{% url 'shop:notfound' %}">Blog </a></li> <!--blog-sidebar-right.html-->
							  
							</ul>
						</li>
						<li><a href="{% url 'shop:contact' %}"><span>Contact</span></a></li> <!--contact.html-->
				
						<li class="dropdown">
								{% if request.user.is_authenticated %}
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<span>Welcome  {{ request.user.username }}</span>
									<i class="fa fa-caret-down"></i>
								</a>
	
								<ul class="dropdown-menu">
									<li><a href="/logout">Logout</a></li> 
									
								</ul>
							</li>
							{% else %}
					<li><a href="{% url 'shop:contact' %}"><span></span></a></li>
				        	{% endif %}
					</ul>
					
					<!-- Header Nav Links End -->
				</div>
			</div>
		</div>
	</header>
		<!-- Header Navbar End -->
	



<!-- end of new nav --------------------------------------------------------------------------->

shop/templates/shop/navbar2.html
{% load static %}
{% load bootstrap4 %}
<nav>

<!--  header Login signup nav  ------------>
<div class="header" id="home">
	<div class="container">
			
		<ul class="nav navbar-right">
				<li class="dropdown">
			      	{% if request.user.is_authenticated %}
					         <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">Welcome  {{ request.user.username }}<b class="caret"></b></a>
							<ul class="dropdown-menu">
							     <li><a href="/logout" style="color:black">logout</a></li>
							</ul>
				</li>
		</ul>
					        	{% else %}
	   <ul>
		    <li> <a href="/accounts/login"><i aria-hidden="true"></i> Sign In </a></li>
		   	<li> <a href="/admin"><i class="fa fa-unlock-alt"aria-hidden="true"></i>Admin Login</a></li>
					          {% endif %}
		</ul>
	</div>
</div>
<!--  //end of header Login signup nav  ----------------------------------------->

    <!-- Preloader Start -->
    <div id="preloader">
        <div class="preloader--inner"></div>
    </div>
    <!-- Preloader End -->


            <!-- Header Navbar Start -->
            <div class="header--navbar navbar bg-black" data-trigger="sticky">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle style--1 collapsed" data-toggle="collapse" data-target="#headerNav">
                            <span class="sr-only">Toggle Navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <!-- Header Navbar Logo Start -->
                       
                        <!-- Header Navbar Logo End -->
                    </div>

                    <div id="headerNav" class="navbar-collapse collapse float--right">
                        <!-- Header Nav Links Start -->
                        <ul class="header--nav-links style--1 nav ff--primary">
                            <li class="dropdown active">
                                <a href="{% url 'shop:home' %}" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Home</span>
                                    <i class="fa fa-caret-down"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li class="active"><a href="{% url 'shop:home' %}"><span>Welcome</span></a></li>
                                  
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Community</span>
                                    <i class="fa fa-caret-down"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'shop:notfound' %}"><span>Activity</span></a></li>
                                    <li><a href="{% url 'shop:notfound' %}"><span>Members</span></a></li>
                                    <li><a href="{% url 'shop:notfound' %}"><span>Groups</span></a></li>
                                </ul>
                            </li>
                            
                            <li class="dropdown megamenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Explore</span>
                                    <i class="fa fa-caret-down"></i>
                                </a>

                                <div class="dropdown-menu">
                                    <div class="row">
                                        <ul class="col-md-2">
                                            <li><a href="{% url 'shop:notfound' %}">Members</a></li>
                                            <li><a href="{% url 'shop:notfound' %}">Groups</a></li>
                                            <li><a href="{% url 'shop:notfound' %}">Site Wide Activity</a></li>
                                            
                                        </ul>

                                   
                                        
                                        <ul class="col-md-2">
                                           
                                            <li><a href="{% url 'shop:notfound' %}">Topics</a></li>
                                            
                                        </ul>
                                        
                                        <ul class="col-md-2">
                                            <li><a href="{% url 'shop:product_list' %}">Shop</a></li> <!-- Products.html-->
                                            <!-- <li><a href="product-details.html">Product Details</a></li>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="checkout.html">Checkout</a></li>
                                            <li><a href="#">Dummy</a></li> -->
                                        </ul>
                                        
                                        <ul class="col-md-2">
                                            <li><a href="{% url 'shop:notfound' %}">Blog</a></li >  <!--blog-sidebar-right.html-->
                                            <!-- <li><a href="blog-sidebar-left.html">Blog Sidebar Left</a></li>
                                            <li><a href="blog-details.html">Blog Details</a></li>
                                            <li><a href="#">Dummy</a></li>
                                            <li><a href="#">Dummy</a></li> -->
                                        </ul>
                                        
                                        <ul class="col-md-2">
                                            <li><a href="{% url 'shop:notfound' %}">About</a></li> <!--about.html-->
                                            <li><a href="{% url 'shop:notfound' %}">FAQ</a></li>     <!--faq.html-->
                                            <li><a href="{% url 'shop:notfound' %}">Contact</a></li>  <!--contact.html-->
                                            <!-- <li><a href="coming-soon.html">Coming Soon</a></li>
                                            <li><a href="404.html">404</a></li> -->
                                        </ul>
                                    </div>
                                </div>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Products</span>
                                    <i class="fa fa-caret-down"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'shop:product_list' %}">Shop</a></li> <!--products.htm-->
                                    <!-- <li><a href="product-details.html">Product Details</a></li> 
                                    <li><a href="cart.html">Cart</a></li> 
                                    <li><a href="checkout.html">Checkout</a></li>  -->
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Blog</span>
                                    <i class="fa fa-caret-down"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'shop:notfound' %}">Blog </a></li> <!--blog-sidebar-right.html-->
                                  
                                </ul>
                            </li>
                            <li><a href="{% url 'shop:notfound' %}"><span>Contact</span></a></li> <!--contact.html-->
                        </ul>
                      
                        <!-- Header Nav Links End -->
                    </div>
                </div>
            </div>
            <!-- Header Navbar End -->
        </header>